version: '3'

services:

  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    ports:
      # the standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: whiterabbit
      RABBITMQ_DEFAULT_PASS: beyondthemirror
    networks:
      - network

  qserve:
    build: .
    ports:
      - '8080:80'
      - '8443:443'
    environment:
      RABBITMQ_USER: whiterabbit
      RABBITMQ_PASS: beyondthemirror
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 15672
      RABBITMQ_EXCHANGE: exchange
      RABBITMQ_QUEUE: exchange.q1
      RABBITMQ_ROUTING_KEY: exchange.q1
    networks:
      - network


networks:
  network: {}
