version: '3'

services:

  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    ports:
      # the standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    networks:
      - network

  proxy:
    build: .
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
    networks:
      - network


networks:
  network: {}
